spring.application.name=ifbank

# Driver MySQL
spring.datasource.dbcp2.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate

# Conexo com MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ifbank
spring.datasource.username=root
spring.datasource.password=root

# Mostrar SQL gerado pelo JPA nos logs
spring.jpa.show-sql=true

server.port=8081